version: "3.9"

services:
  server:
    container_name: praktikum-server
    image: praktikum-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: 3001
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app-net
    environment:
      SERVER_PORT: 3001
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres
    command: sh -c "./wait-for postgres:5432 -- node ./index.js"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres
    networks:
      - app-net
    volumes:
      - /var/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    networks:
      - app-net
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_PORT: 5050
    volumes:
      - /var/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  webserver:
    container_name: nginx
    image: nginx:1.25
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email p.bologan@yandex.ru --agree-tos --no-eff-email --staging -d wizards-monopoly.ya-praktikum.tech

networks:
  app-net:
    driver: bridge
