version: "3.9"

services:
  server:
    container_name: prakticum-server
    image: prakticum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app-net
    environment:
      SERVER_PORT: ${SERVER_PORT}
    command: sh -c "./wait-for postgres:${POSTGRES_PORT} -- node ./index.js"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgresql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - app-net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - ./.env
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    networks:
      - app-net
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - ./tmp/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  app-net:
    driver: bridge
