name: Build And Deploy

on:
  push:
    branches:
      - ya-deploy

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stop containers
        run: sudo docker compose -f docker-compose.cloud.yml down
      - name: Start containers
        run: sudo docker compose -f docker-compose.cloud.yml up -d --build

